import { WorklogMapping } from '../shared/types';

/**
 * Determines whether an incoming sync event should be skipped because it
 * has already been applied (idempotency) or because it was generated by
 * our own last write to the *other* system (loop prevention).
 */
export function shouldSkipSyncEvent(
  existingMapping: WorklogMapping | undefined,
  incoming: { origin: 'jira' | 'kimai'; hash: string },
): boolean {
  if (!existingMapping) {
    return false;
  }

  // Same content hash already recorded: this is a replay/duplicate event.
  if (existingMapping.lastHash && existingMapping.lastHash === incoming.hash) {
    return true;
  }

  return false;
}

/**
 * Computes a stable content hash for a worklog/timesheet payload so that
 * repeated deliveries of the same logical change can be detected.
 */
export function computeContentHash(fields: Record<string, unknown>): string {
  const normalized = Object.keys(fields)
    .sort()
    .map((key) => `${key}=${JSON.stringify(fields[key])}`)
    .join('&');

  let hash = 0;
  for (let i = 0; i < normalized.length; i += 1) {
    hash = (hash * 31 + normalized.charCodeAt(i)) | 0;
  }
  return hash.toString(16);
}

export function mergeMapping(
  existing: WorklogMapping | undefined,
  updates: Partial<WorklogMapping> & Pick<WorklogMapping, 'jiraWorklogId' | 'kimaiTimesheetId'>,
): WorklogMapping {
  return {
    jiraIssueId: updates.jiraIssueId ?? existing?.jiraIssueId ?? '',
    jiraIssueKey: updates.jiraIssueKey ?? existing?.jiraIssueKey ?? '',
    jiraWorklogId: updates.jiraWorklogId,
    kimaiTimesheetId: updates.kimaiTimesheetId,
    origin: updates.origin ?? existing?.origin ?? 'jira',
    lastSyncedAt: updates.lastSyncedAt ?? new Date().toISOString(),
    lastHash: updates.lastHash ?? existing?.lastHash,
  };
}
